export const USERS_LOAD_START = 'USERS_LOAD_START';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_ERROR = 'USERS_LOAD_ERROR';
export const A_USER_LOAD_SUCCESS = 'A_USER_LOAD_SUCCESS';
