export const PROJECTS_LOAD_START = 'PROJECTS_LOAD_START';
export const PROJECTS_LOAD_SUCCESS = 'PROJECTS_LOAD_SUCCESS';
export const PROJECTS_LOAD_ERROR = 'PROJECTS_LOAD_ERROR';
export const A_PROJECT_LOAD_SUCCESS = 'A_PROJECT_LOAD_SUCCESS';
export const A_USER_ASSIGNED = 'A_PROJECT_ASSIGNED';
